// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEBsDXmAUazZCNbeC8tJfssXdT2uePufw',
    appId: '1:407790503210:web:e5e4a2bfffc188c2780a53',
    messagingSenderId: '407790503210',
    projectId: 'spendly-8fb19',
    authDomain: 'spendly-8fb19.firebaseapp.com',
    storageBucket: 'spendly-8fb19.firebasestorage.app',
    measurementId: 'G-DM304Z6BB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAl7IDZIxqeki0jGYTbmm5ZryTstbnkSE',
    appId: '1:407790503210:android:14f1590a532676f5780a53',
    messagingSenderId: '407790503210',
    projectId: 'spendly-8fb19',
    storageBucket: 'spendly-8fb19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx9elbPBdZdvSkVIcxrbU86-NTR4LaaMQ',
    appId: '1:407790503210:ios:09d4ec7f9d73414a780a53',
    messagingSenderId: '407790503210',
    projectId: 'spendly-8fb19',
    storageBucket: 'spendly-8fb19.firebasestorage.app',
    iosBundleId: 'com.spendly.spendly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx9elbPBdZdvSkVIcxrbU86-NTR4LaaMQ',
    appId: '1:407790503210:ios:09d4ec7f9d73414a780a53',
    messagingSenderId: '407790503210',
    projectId: 'spendly-8fb19',
    storageBucket: 'spendly-8fb19.firebasestorage.app',
    iosBundleId: 'com.spendly.spendly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEBsDXmAUazZCNbeC8tJfssXdT2uePufw',
    appId: '1:407790503210:web:41cf2a2246988f64780a53',
    messagingSenderId: '407790503210',
    projectId: 'spendly-8fb19',
    authDomain: 'spendly-8fb19.firebaseapp.com',
    storageBucket: 'spendly-8fb19.firebasestorage.app',
    measurementId: 'G-DJJHQJLTK6',
  );
}
